LSTchannels = [["BBC1",					"96",		"channel_bbc1_hd",				"tv",		108],
               ["BBC2",					"105",		"channel_bbc2_hd",				"tv",		162],
               ["BBC3",					"45",		"channel_bbc3_hd",				"tv",		163],
               ["BBC4",					"47",		"channel_bbc4_hd",				"tv",		164],
               ["ITV",					"28",		"channel_itv1_hd",				"tv",		113],
               ["ITV2",					"185",		"channel_itv2",					"tv",		115],
               ["ITV3",					"1859",		"channel_itv3",					"tv",		117],
               ["ITV4",					"1961",		"channel_itv4",					"tv",		118],
               ["Channel 4",			"2056",		"channel_4_hd",					"tv",		142],
               ["E4",					"158",		"channel_e4",					"tv",		144],
               ["More4",				"1959",		"channel_more4",				"tv",		147],
               ["Channel 5",			"2615",		"channel_five_hd",				"tv",		150],
               ["dave",					"2050",		"channel_dave",					"tv",		128],
               ["Sky1",					"248",		"channel_sky1",					"tv",		109],
               ["Sky2",					"922",		"channel_sky2",					"tv",		121],
               ["Pick",					"1963",		"channel_pick",					"tv",		123],
               ["syfy",					"2212",		"channel_syfy",					"tv",		135],
               ["TLC",					"",			"channel_tlc",					"tv",		167],
               ["MTV",					"202",		"channel_mtv",					"tv",		134],
               ["Good Food",			"2136",		"channel_goodfood",				"tv",		260],
               ["Food Network",			"2185",		"channel_foodnetwork",			"tv",		287],
               ["Film4",				"2617",		"channel_film4_hd",				"tv",		429],
               ["Movies 24",			"2704",		"channel_movies24",				"tv",		419],
               ["TCM",					"271",		"channel_tcm",					"tv",		415],
               ["Watch",				"2115",		"channel_watch",				"tv",		124],
               ["Gold",					"288",		"channel_gold",					"tv",		126],
               ["Fox",					"1461",		"channel_fox",					"tv",		157],
               ["Universal",			"180",		"channel_universal",			"tv",		137],
               ["Comedy Central",		"1061",		"channel_comedycentral",		"tv",		132],
               ["Challenge",			"131",		"channel_challenge",			"tv",		139],
               ["Discovery",			"147",		"channel_discovery",			"tv",		211],
               ["Discovery Science",	"153",		"channel_discoveryscience",		"tv",		219],
               ["Discovery History",	"2668",		"channel_discoveryhistory",		"tv",		222],
               ["Yesterday",			"801",		"channel_yesterday",			"tv",		206],
               ["H2",					"2559",		"channel_h2",					"tv",		236],
               ["BBC News",				"48",		"channel_bbcnews_hd",			"tv",		604],
               ["Sky News",				"256",		"channel_skynews",				"tv",		602],
               ["Kerrang!",				"191",		"channel_kerrang",				"tv",		342],
               ["Heat",					"",			"channel_heat",					"radio",	338],
               ["Capital FM",			"",			"channel_capitalfm",			"radio",	958],
               ["BBC Radio 1",			"",			"channel_bbcradio1",			"radio",	901],
               ["Classic FM",			"",			"channel_classicfm",			"radio",	922],
               ["Heart",				"",			"channel_heart",				"radio",	918],
               ["Planet Rock",			"",			"channel_planetrock",			"radio",	924],
               ["Gold Radio",			"",			"channel_goldradio",			"radio",	923]]