class enum_channels:

    LSTchannels = []
    LSTchannels.append([108,	"BBC1",					"96",		"channel_bbc1_hd",				"tv"])
    LSTchannels.append([162,	"BBC2",					"105",		"channel_bbc2_hd",				"tv"])
    LSTchannels.append([163,	"BBC3",					"45",		"channel_bbc3_hd",				"tv"])
    LSTchannels.append([164,	"BBC4",					"47",		"channel_bbc4_hd",				"tv"])
    LSTchannels.append([113,	"ITV",					"28",		"channel_itv1_hd",				"tv"])
    LSTchannels.append([115,	"ITV2",					"185",		"channel_itv2",					"tv"])
    LSTchannels.append([117,	"ITV3",					"1859",		"channel_itv3",					"tv"])
    LSTchannels.append([118,	"ITV4",					"1961",		"channel_itv4",					"tv"])
    LSTchannels.append([142,	"Channel 4",			"2056",		"channel_4_hd",					"tv"])
    LSTchannels.append([144,	"E4",					"158",		"channel_e4",					"tv"])
    LSTchannels.append([147,	"More4",				"1959",		"channel_more4",				"tv"])
    LSTchannels.append([150,	"Channel 5",			"2615",		"channel_five_hd",				"tv"])
    LSTchannels.append([128,	"dave",					"2050",		"channel_dave",					"tv"])
    LSTchannels.append([109,	"Sky1",					"248",		"channel_sky1",					"tv"])
    LSTchannels.append([121,	"Sky2",					"922",		"channel_sky2",					"tv"])
    LSTchannels.append([123,	"Pick",					"1963",		"channel_pick",					"tv"])
    LSTchannels.append([135,	"syfy",					"2212",		"channel_syfy",					"tv"])
    LSTchannels.append([167,	"TLC",					"",			"channel_tlc",					"tv"])
    LSTchannels.append([134,	"MTV",					"202",		"channel_mtv",					"tv"])
    LSTchannels.append([260,	"Good Food",			"2136",		"channel_goodfood",				"tv"])
    LSTchannels.append([287,	"Food Network",			"2185",		"channel_foodnetwork",			"tv"])
    LSTchannels.append([429,	"Film4",				"2617",		"channel_film4_hd",				"tv"])
    LSTchannels.append([419,	"Movies 24",			"2704",		"channel_movies24",				"tv"])
    LSTchannels.append([415,	"TCM",					"271",		"channel_tcm",					"tv"])
    LSTchannels.append([124,	"Watch",				"2115",		"channel_watch",				"tv"])
    LSTchannels.append([126,	"Gold",					"288",		"channel_gold",					"tv"])
    LSTchannels.append([157,	"Fox",					"1461",		"channel_fox",					"tv"])
    LSTchannels.append([137,	"Universal",			"180",		"channel_universal",			"tv"])
    LSTchannels.append([132,	"Comedy Central",		"1061",		"channel_comedycentral",		"tv"])
    LSTchannels.append([139,	"Challenge",			"131",		"channel_challenge",			"tv"])
    LSTchannels.append([211,	"Discovery",			"147",		"channel_discovery",			"tv"])
    LSTchannels.append([219,	"Discovery Science",	"153",		"channel_discoveryscience",		"tv"])
    LSTchannels.append([222,	"Discovery History",	"2668",		"channel_discoveryhistory",		"tv"])
    LSTchannels.append([206,	"Yesterday",			"801",		"channel_yesterday",			"tv"])
    LSTchannels.append([236,	"H2",					"2559",		"channel_h2",					"tv"])
    LSTchannels.append([604,	"BBC News",				"48",		"channel_bbcnews_hd",			"tv"])
    LSTchannels.append([602,	"Sky News",				"256",		"channel_skynews",				"tv"])
    LSTchannels.append([342,	"Kerrang!",				"191",		"channel_kerrang",				"tv"])
    LSTchannels.append([338,	"Heat",					"",			"channel_heat",					"radio"])
    LSTchannels.append([958,	"Capital FM",			"",			"channel_capitalfm",			"radio"])
    LSTchannels.append([901,	"BBC Radio 1",			"",			"channel_bbcradio1",			"radio"])
    LSTchannels.append([922,	"Classic FM",			"",			"channel_classicfm",			"radio"])
    LSTchannels.append([918,	"Heart",				"",			"channel_heart",				"radio"])
    LSTchannels.append([924,	"Planet Rock",			"",			"channel_planetrock",			"radio"])
    LSTchannels.append([923,	"Gold Radio",			"",			"channel_goldradio",			"radio"])