LSTchannels = [[108,	"BBC1",					"96",		"channel_bbc1_hd",				"tv"],
               [162,	"BBC2",					"105",		"channel_bbc2_hd",				"tv"],
               [163,	"BBC3",					"45",		"channel_bbc3_hd",				"tv"],
               [164,	"BBC4",					"47",		"channel_bbc4_hd",				"tv"],
               [113,	"ITV",					"28",		"channel_itv1_hd",				"tv"],
               [115,	"ITV2",					"185",		"channel_itv2",					"tv"],
               [117,	"ITV3",					"1859",		"channel_itv3",					"tv"],
               [118,	"ITV4",					"1961",		"channel_itv4",					"tv"],
               [142,	"Channel 4",			"2056",		"channel_4_hd",					"tv"],
               [144,	"E4",					"158",		"channel_e4",					"tv"],
               [147,	"More4",				"1959",		"channel_more4",				"tv"],
               [150,	"Channel 5",			"2615",		"channel_five_hd",				"tv"],
               [128,	"dave",					"2050",		"channel_dave",					"tv"],
               [109,	"Sky1",					"248",		"channel_sky1",					"tv"],
               [121,	"Sky2",					"922",		"channel_sky2",					"tv"],
               [123,	"Pick",					"1963",		"channel_pick",					"tv"],
               [135,	"syfy",					"2212",		"channel_syfy",					"tv"],
               [167,	"TLC",					"",			"channel_tlc",					"tv"],
               [134,	"MTV",					"202",		"channel_mtv",					"tv"],
               [260,	"Good Food",			"2136",		"channel_goodfood",				"tv"],
               [287,	"Food Network",			"2185",		"channel_foodnetwork",			"tv"],
               [429,	"Film4",				"2617",		"channel_film4_hd",				"tv"],
               [419,	"Movies 24",			"2704",		"channel_movies24",				"tv"],
               [415,	"TCM",					"271",		"channel_tcm",					"tv"],
               [124,	"Watch",				"2115",		"channel_watch",				"tv"],
               [126,	"Gold",					"288",		"channel_gold",					"tv"],
               [157,	"Fox",					"1461",		"channel_fox",					"tv"],
               [137,	"Universal",			"180",		"channel_universal",			"tv"],
               [132,	"Comedy Central",		"1061",		"channel_comedycentral",		"tv"],
               [139,	"Challenge",			"131",		"channel_challenge",			"tv"],
               [211,	"Discovery",			"147",		"channel_discovery",			"tv"],
               [219,	"Discovery Science",	"153",		"channel_discoveryscience",		"tv"],
               [222,	"Discovery History",	"2668",		"channel_discoveryhistory",		"tv"],
               [206,	"Yesterday",			"801",		"channel_yesterday",			"tv"],
               [236,	"H2",					"2559",		"channel_h2",					"tv"],
               [604,	"BBC News",				"48",		"channel_bbcnews_hd",			"tv"],
               [602,	"Sky News",				"256",		"channel_skynews",				"tv"],
               [342,	"Kerrang!",				"191",		"channel_kerrang",				"tv"],
               [338,	"Heat",					"",			"channel_heat",					"radio"],
               [958,	"Capital FM",			"",			"channel_capitalfm",			"radio"],
               [901,	"BBC Radio 1",			"",			"channel_bbcradio1",			"radio"],
               [922,	"Classic FM",			"",			"channel_classicfm",			"radio"],
               [918,	"Heart",				"",			"channel_heart",				"radio"],
               [924,	"Planet Rock",			"",			"channel_planetrock",			"radio"],
               [923,	"Gold Radio",			"",			"channel_goldradio",			"radio"]]


